### PR TITLE
Content curation

### PR DESCRIPTION
**Pull request by Antrikshy**
This marks a beginning of a new era for the central server. All hail content curation!

### CODE REVIEW

**Comment by jamalex** [comment]
[Let there be content!](http://www.starwars.com/games-apps/star-wars-crawl-creator/?55285cb9e4b08f144ab70641)

**Comment by Antrikshy** [comment]
I just added some models for the tree structure. Any refinements required? I may or may not come in today. Just got slammed with some deadlines.

**Comment by jamalex** [comment]
We discussed how the models would be updated. Going to merge this in the meantime so that we have the new app in the branch.

**Comment by Antrikshy** [comment]
@jamalex You mean there are updates on our plans for models?

**Pull request merged**
