### PR TITLE
Clean up central server a tad; amend README

### PR DESCRIPTION
**Pull request by MCGallaspy**
The commit message:

```
remove fle_utils.handlebars, fle_utils.backbone references; they're gone.

Add pycharm files to gitignore

Update README

remove unused import

use distributed bundles in base template
```

We'll also wish to update the submodule after https://github.com/learningequality/ka-lite/pull/4465 has been merged; otherwise errors will result.

@rtibbles @aronasorman someone wanna take a peek?

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Some styling seems to have been lost, but otherwise seems to be working -- at least an account can be created and there are no js errors on page load for org management:

ss2

Will open styling problem as separate issue.

**Comment by MCGallaspy** [comment]
Ecosystem tests pass (my original motivation). Will look at other failures, too.

**Comment by MCGallaspy** [comment]
About the tests:
* FAQ tests appear to be failing because of a poorly-crafted fixtures. Can create new ones.
* Not sure why reverse fails for the given name... the url works just fine. Could be an import issue?
* The tests with missing alerts pass locally, so I'm not worried about it.

That said, there are quite a few display issues. A lot of styling seems to be gone, probably because it came form the distributed server and we're not including some of those assets.

Recommend merging this to allow other issues to be tested/tackled simultaneously.

**Comment by MCGallaspy** [comment]
Looks much better -- the same as hub.learningequality.org, which is a good sign. Comments about test failures still apply. Still recommend merging so we can work out other issues simultaneously.

**Comment by rtibbles** [comment]
I see nothing too alarming.

**Pull request merged**
